name: Download .po

on:
  push:
  branches:
    - main

jobs:
  convertpo:
    name: Convert .po
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Convert .po to .mo
        run: |
          sudo apt install gettext -y
          ./convert_po2mo.sh
      - name: Commit .mo files
        uses: stefanzweifel/git-auto-commit-action@v4