name: Create POT

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  markdownlint:
    name: Update .pot file
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build hestiacp.pot
        run: |
          git clone https://github.com/hestiacp/hestiacp
          sudo apt install gettext -y
          ./hst_scan_i18n.sh
      - name: Commit new .pot file
        uses: stefanzweifel/git-auto-commit-action@v4
