name: Create POT

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  markdownlint:
    name: Clone code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build hestiacp.pot
        run: |
          git clone https://github.com/hestiacp/hestiacp
          sudo apt install gettext -y
          ./hst_scan_i18n.sh
