name: Create POT

on:
  schedule:
	- cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update-pot:
	name: Update .pot file
	runs-on: ubuntu-latest
	permissions:
	  contents: write

	steps:
	  - name: Checkout code
		uses: actions/checkout@v3
	  - name: crowdin action
		uses: crowdin/github-action@v1
		with:
		  upload_sources: false
		  upload_translations: false
		  download_translations: true
		env:
		  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
		  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
		  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
	  - name: Commit new .pot file
	  	uses: stefanzweifel/git-auto-commit-action@v4